### ISSUE TITLE
Are we always supposed to queue a notification task when there are buffered entries to see?

### ISSUE THREAD

**Issue by pshaughn** [w3c/performance-timeline#158]
https://wpt.fyi/results/performance-timeline/multiple-buffered-flag-observers.any.html?label=experimental&label=master&aligned has inconsistent results, and I think Firefox's timeout is what a literal reading of the spec expects. (test source at https://github.com/web-platform-tests/wpt/blob/master/performance-timeline/multiple-buffered-flag-observers.any.js)

We buffer some marks, wait long enough for tasks to resolve (the 100ms timeout), then add a new buffered PerformanceObserver expecting it to see those already-buffered marks. The test expects that new observer's callback to be called so it can see the marks, but in the spec, nothing says to call it now; https://w3c.github.io/user-timing/#mark-method and the task it made have already finished happening.

**Comment by npm1** [comment]
Hi, the mark method seems fine to me. The observe() method https://w3c.github.io/performance-timeline/#observe-method is actually the problem. When the buffered flag is set, we may append entries to the observer's buffer. This also means that we may need to queue the task to dispatch the observer callbacks. Otherwise as you note, if there is no such task then the observer could never receive the entries. I'll fix this, thanks for pointing out this problem.
