### ISSUE TITLE
When should a UA clear its entry buffers?

### ISSUE THREAD

**Issue by sefeng211** [w3c/performance-timeline#178]
The spec doesn't specify when a UA should clear the entry buffers. 

Say the page has been running for days, should the UA be able to clear the entry buffers since the cached buffers are likely no longer useful? 

This is somewhat related to #101, however, #101 is more specific about under memory pressure condition. 

@smaug---- @npm1

**Comment by smaug----** [comment]
FWIW, I was asking this question from @sefeng211 in the context of PerformanceEventTiming.

**Comment by npm1** [comment]
Sorry for missing the ping here @sefeng211 

We discussed in the call. The idea is that the size-bounded buffers* are used to keep track of initial entries, while analytics has the chance to register PerformanceObservers. So there is no need to clear these buffers. There's a question around whether it's worth clearing them when certain conditions are met and we are 'confident' that the data won't be used, but I don't think we reached consensus on a reasonable heuristic here and any such heuristic could hurt developer expectations due to increased inconsistency. Closing but let me know if I missed something.

* bounded except for User Timing: https://w3c.github.io/timing-entrytypes-registry/#registry
