### ISSUE TITLE
Annotation of performance entries

### ISSUE THREAD

**Issue by eliperelman** [w3c/performance-timeline#2]
From: http://lists.w3.org/Archives/Public/public-web-perf/2014Feb/0056.html

@jatinder: Another piece feedback I’ve heard on the Timing APIs is that it would be great if we provided the ability to “annotate” entries with app-specific meta data. For example, if someone wanted to add in specific information on what the server was doing during a certain time period they could annotate the timeline so you can see the complete client and server side interaction. Additionally, one could also annotate why a measure might have taken as long as it did (e.g. how many items were rendered, which column was sorted, etc.). Something like performance.annotateMeasure(“measureName”, “keyName”, “value”). Does something like this sound remotely interesting?

Juan Carlos Estibariz: The annotations would be very useful, and it would be even better if it was possible to add annotations directly from the server (e.g. by adding a header defined by this specification), this would allow direct correlation between client side and server side performance measurements.

@josh: User timings in the response header sounds elegant.
We currently shove all our server timings into a hidden element in the
page footer as data- attributes. Then we have to parse these out on
page load.

---

Having the ability to somehow annotate an entry with custom metadata would open the doorway to some very interesting tooling improvements with multi-page UIs, e.g. multi-frame pages or multi-process apps like in Firefox OS.

Is there enough information available to work towards this? Based on @jatinder's recommendation I see:

```
partial interface Performance {
  void annotateMark(DOMString markName, DOMString key, DOMString value);
  void annotateMeasure(DOMString measureName, DOMString key, DOMString value);
};
```

**Comment by igrigorik** [comment]
Reading through the thread once over...

* The server timing use cases are now addressed via (appropriately named :)) [Server Timing spec](w3c.github.io/server-timing).
* @nicjansma: custom annotations beyond current "markName": still seems to me that much of this can be encoded in the mark name itself? That said, if you think there is a strong need for this, let's open a bug on User Timing repo?
* @eliperelman: if I'm following your use case of "linking records", perhaps this can address it: https://github.com/w3c/performance-timeline/pull/9#issuecomment-89042906 ? 

Since this seems like a meta-bug, can we close this one and/or split other discussions into separate issues?

**Comment by nicjansma** [comment]
Opened a separate issue in UserTiming https://github.com/w3c/user-timing/issues/3

**Comment by igrigorik** [comment]
Closing this, let's continue the User Timing discussion in https://github.com/w3c/user-timing/issues/3.
