### ISSUE TITLE
Behavior when invalid attribute is specifed for getEntries filter

### ISSUE THREAD

**Issue by hiikezoe** [w3c/performance-timeline#30]
In the current spec, if specified filter attribute is not in FilterOptions members, the filter affects nothing, so getEntries with invalid attribute returns all entries. Is this behavior is intentional?

For reference see https://bugzilla.mozilla.org/show_bug.cgi?id=1165796#c10

**Comment by igrigorik** [comment]
Yes, that was intentional. We want to be flexible to allow for cases where some browsers may have event types that others do not and we want those types to be ignored without causing an error - i.e. as a developer I can just list all the types I'm interested in and browser should deliver what it supports.

That said, if you have a list of invalid types, then getting the full firehose also doesn't seem right. Perhaps we should have a special check for this case and throw an error? Not sure if there is a clean way to handle this via IDL, or if we'd need another step in the processing algorithm.

/cc @bzbarsky @toddreifsteck @plehegar

**Comment by bzbarsky** [comment]
Per IDL, dictionaries just ignore properties they don't know anything about.

So if you want some other sort of processing, you'd have to do it manually (and you need to be _really_ careful about how you define it, then).

**Comment by igrigorik** [comment]
Resolved via #35, see: https://w3c.github.io/performance-timeline/#widl-PerformanceObserverInit-typeFilter. 

Closing, feel free to reopen if there is more to be done here.
