### ISSUE TITLE
performance.timing shouldn't be deprecated

### ISSUE THREAD

**Issue by rniwa** [w3c/performance-timeline#68]
We tried to ship `performance.now()` without `performance.timing` and that caused a whole bunch of compatibility issues to an extent we couldn't ship Safari.

I don't think we can deprecate this feature anytime soon.

**Comment by toddreifsteck** [comment]
It seems the spec could be improved with a non-normative note stating this is in heavy use by web developers today so UAs should implement, but Navigation Timing 2 is the preferred interface for web developers.

**Comment by rniwa** [comment]
Well, I think we probably need to separate browser implementation conformance & author conformance requirements as done in the HTML specification. I think nothing that they're historical and authors are strongly discouraged to use them is good but I think we need to make it clear that `navigation.timing` is a conformance requirement for browser engines.

**Comment by igrigorik** [comment]
Based on the discussion on the call earlier this week..

We kept `performance.timing` and all the related definitions in the draft precisely because we believed that removing it would be impossible in short~medium term. Implementers will need to support both. However, we wanted to actively discourage use of NT1 interface + provide a clear visual indication when looking at its definition -- hence the current legacy "branding". Prior to adding the visual we had other bugs where folks were getting confused about which attribute definition they were looking at (both interfaces overlap). 

On the call, the proposal was to add a non-normative note at the top of the NT1 section and clarify that the interface is required for implementers, but discouraged for web developers. 

Would that work? Other suggestions?

**Comment by rniwa** [comment]
First, I don't think the section for `PerformanceTiming` should be named as "historical" as that term is typically used to refer to historical APIs that no longer need to be supported. We typically use "obsolete" to refer to features that are non-comfortant for authors to use but are required by browser engines to implement. e.g. see https://html.spec.whatwg.org/#obsolete

Second, the section shouldn't look as if it's optional or appendix. It should either be its on section 8 or be merged into 4 with normative text saying this is an obsolete feature author should not be using.

**Comment by igrigorik** [comment]
@rniwa thanks, fixed in w3c/navigation-timing@b9eee39.
