### ISSUE TITLE
Define buffering behaviors & hooks for queued (PerformanceObserver) entries

### ISSUE THREAD

**Issue by igrigorik** [w3c/performance-timeline#81]
We recently (see #76) added an optional flag to "queue an entry" that allows the caller to optionally append the entry to the [performance entry buffer](https://w3c.github.io/performance-timeline/#dfn-performance-entry-buffer).. For example, Long Tasks or Server Timing can set this to `true` while before onload to allow developers to register and retrieve any LT/ST records captured between start of page load and max(time when they register observer, onloadend). 

A few interactions that we did not address:
1. How does performance entry buffer interact with other buffers defined by individual specs? E.g. ResourceTiming defines own buffer with methods to query and clear it. 
  - When RT's buffer is cleared, does that affect the `performance entry buffer`?
1. Do we want to set a global cap on the `performance entry buffer`?
  - What happens when the limit is reached, do we start dropping items on the floor?

_Sidenote: moving forward we're not planning on adding more type-specific buffers.. Instead, we want to encourage use of PerfObserver. So, this is mostly an exercise in backwards compat and to make sure that we can pave a clean path for existing users of RT/NT/UT._

---

For (1), my hunch is "no", calls to clear type-specific buffers should not clear the performance entry buffer. This does mean that we might end up with some double book-keeping, but one of the motivating reasons for PerfObserver was to resolve the race conditions created by consumers clearing buffers from under each other. As such, I think I propose we treat them as separate entities: it should be possible to clear the RT buffer and still use PerfObserver with `buffered: true` to get all the entries queued before onload.

For (2), my hunch is "yes", and we should probably recommend a minimum ~ user agent should allow a minimum of XXXX entries to be queued, and once full the items are silently discarded.

/cc @cvazac @nicjansma @toddreifsteck

**Comment by igrigorik** [comment]
Based on the [discussion at the WebPerf F2F](https://docs.google.com/document/d/1fcWpKZhJdrmBlpYUB2wIx42svo9zqojoJMZg8aY7E7Y/edit#bookmark=id.a3cjs2ikkil), we converged on: 

- Each spec defines a buffer with custom buffer size (depends on type of data, etc)
- Performance Timeline will buffer events until buffer is full. When the buffer is full...
  - Keep the first N entries, drop overflow
 - Buffer is **not** cleared at onload, but under memory pressure UA _may_ clear buffers
 - Some specs may provide additional methods to manipulate their buffer (e.g. ResourceTiming), but this is not a requirement.

Does that sound correct? Assuming the answer is yes, the tactical work here is...

- I think we can back out some of the changes we landed in https://github.com/w3c/performance-timeline/pull/76. Specifically, the buffered flag for the `queue` step.
- We need to agree on how we want to structure the hooks. One take could be:
  - Performance Timeline defines performance entry buffer (as it does today), which is segmented by type of entries
  - Upstream specs define max buffer size for their type, which is enforced by PerfTimeline.
    - We should define "add to performance entry buffer" as a concept in PerfTimeline.
    - Upstream specs call add step and pass in entry to perf timeline, which does the rest. This way we don't have to replicate the buffer and and enforcement logic in every spec.
  - PerformanceTimeline's getEntries* queries global performance entry buffer.. as defined today.

@toddreifsteck WDYT, does that seem reasonable?

**Comment by rniwa** [comment]
I'm not certain if we should allow UA to clear buffer at a memory pressure. That would make the API a lot less reliable.

**Comment by igrigorik** [comment]
@rniwa fair enough. Does the rest look reasonable to you?

**Comment by rniwa** [comment]
What's the rationale for each spec to define its own limit? Isn't it easier to have a global limit?

**Comment by igrigorik** [comment]
@rniwa we've all implemented separate buffers for each type, and I think there is a good argument that different types of events (i.e. some specs) may need different limits. As a concrete example, our current limit for ResourceTiming is, arguably, too low: https://github.com/w3c/resource-timing/issues/89. At the same time, I don't think it makes sense to raise the limit to a higher number for all event types.. WDYT?

**Comment by toddreifsteck** [comment]
@igrigorik Here are my thoughts. Does this answer the questions in a way that helps close on the spec update you plan to make?

I assert that the memory pressure needs to stay. UAs will clear the buffers regardless of what the specs say if they can avoid crashing and performance issues due to memory pressure so we should keep that text. It should be a corner case and will not impact the real world for 99.9% of usage.

Upstream specs should define a min and max buffer size.

In general, each spec needs to consider carefully what will occur when buffers are cleared and buffer management is recommended but the Performance Timeline should defer those decisions to each spec/buffer in my opinion.

Should the global Performance Entry buffer we redefined as a merge of the various separate buffers?

**Comment by igrigorik** [comment]
@toddreifsteck thanks, yes that sounds reasonable.

> Should the global Performance Entry buffer we redefined as a merge of the various separate buffers?

Effectively, that is how it is defined today.

**Comment by yoavweiss** [comment]
Going back to this and given the work done on https://github.com/w3c/resource-timing/pull/163, I think it makes sense to move all the buffer processing to a central location. I also think we need to go beyond that and define the "buffer full" behavior and events in a generic way (e.g. In Chromium's implementation, there are a lot of parallels between Resource Timing and Event Timing on that front).

I guess the main question is if we want this to be an L2 blocker, as it's a rather large refactoring.

**Comment by rniwa** [comment]
I don't think it needs to block L2. I think it makes more sense to do it in L3 when we define things in terms of fetch.

**Comment by igrigorik** [comment]
Ditto, I don't think this is an L2 blocker. Also, in a world where PerfObserver is the new default, we may be able to soft deprecate the buffer bits.. `</wishful-thinking>`

**Comment by npm1** [comment]
Discussed this today with @yoavweiss and @tdresser. I'd like to work on this by doing the following:
* Replacing the global buffer with a map entryType->buffer, which probably aligns better with user agent implementations.
* Adding a flag so that each entryType can specify whether its buffer is available from the performance timeline (performance.getEntries()).
* Adding a max size for each entryType. For UserTiming entries it might be infinite? For ResourceTiming, I guess we'd keep the method to change this size. But for other types, the max size cannot be changed.
* When the buffer becomes full, the user agent will no longer buffer any further entries (except for the special processing in ResourceTiming). This is acceptable because these buffers (for future entryTypes) are mostly meant only for support of the buffered flag, they are not meant to be a replacement for PerformanceObserver.

Does this make sense to others? Ideally I'd work on this after we have (re)published Level 2 because all of these changes should be considered L3 as they are only relevant for the buffered flag. Is anyone working on the Level 2 work? I see that the buffered flag PR is quite old (https://github.com/w3c/performance-timeline/commit/b763e5ce7f0d19999982b1c46c937cecfb197825) so if we want to publish using earlier commits then we'd need to pin the commit and then manually revert anything related to the bufferd flag.

**Comment by npm1** [comment]
The work here is done, yay. Closing
